# Generated by Django 3.0.5 on 2020-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(default=0, max_length=3000),
        ),
    ]
