# Generated by Django 3.0.5 on 2020-04-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200406_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandname',
            options={'ordering': ('brand_name',), 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('category_name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='brandname',
            name='brand_slug',
            field=models.CharField(default=models.CharField(max_length=60), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_slug',
            field=models.CharField(default=models.CharField(max_length=60), max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.BrandName'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
