# Generated by Django 3.0.5 on 2020-04-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_accessories',
            field=models.TextField(default='No Accessories Available'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_other_description',
            field=models.TextField(default='No Description Available'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_specification',
            field=models.TextField(default='No Specification Available'),
        ),
    ]
