# Generated by Django 3.0.5 on 2020-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200410_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_other_description',
            field=models.TextField(default='No Description Available'),
        ),
    ]
