# Generated by Django 3.0.5 on 2020-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200410_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='optional_accessories',
            field=models.ImageField(default='static/default_pro_pic.jpg', upload_to='pics'),
        ),
    ]
